### ISSUE TITLE
How do we add the Touch listeners to specific views?

### ISSUE THREAD

**Issue by gouravd** [nisrulz/sensey#13]
How do we add the Touch listeners to specific views?

**Comment by nisrulz** [comment]
@gouravd I haven't tested the lib to work with specific views but I would test that out before I can make a statement about it.

**Comment by k0shk0sh** [comment]
Override this in your custom view and you should be good to go.
```
@Override public boolean dispatchTouchEvent(MotionEvent event) {
    Sensey.getInstance().setupDispatchTouchEvent(event);
    return super.dispatchTouchEvent(event);
}
```

**Comment by nisrulz** [comment]
@gouravd Can you confirm that this is resolved.

**Comment by nisrulz** [comment]
Closing as already answered.

**Comment by gouravd** [comment]
I had to eventually create a wrapper view on top of my views and overridden the dispatch events for these wrapper views.
