### ISSUE TITLE
Proximity detection of a specific distance

### ISSUE THREAD

**Issue by MaximilianKeppeler** [nisrulz/sensey#14]
In my use case I need to trigger a special event at a customizable distance. The onNear and onFar methods work incredibly good. But the distance, when these are triggers, is too low for my use case. 

**There are 2 options I thought of.**

**A onDistance method**, which will be triggered at a specific distance, which was defined/ set before. 

**No additional method, just changing the distance when onNear and onFar are triggered.** This is actually my preferred option, since it keeps the behavior of the onNear and onFar methods but the trigger event can be placed at a specific distance. That would be pretty nice. 

In my use case, a distance of between (around) 4 -15 cm must be set. Though that distance must be set dynamically. 

I hope it's understandable. Thank you very much in advance. 
This library is really amazing - fantastic work!

_Edited my comment for a better tangibility._

**Comment by NielsMasdorp** [comment]
`startProximityDetection` method can take a `float` threshold parameter. Isn't that what you mean?

**Comment by MaximilianKeppeler** [comment]
Doesn't seem to have any influence on my device. I variegated with the value, but the threshold was still around 2 cm / as without any float value.

**Comment by NielsMasdorp** [comment]
Weird, according to the Android Developer documentation the sensor usually returns the distance in cm so calling `startProximityDetection(10f, this)` should make it trigger at 10cm. Maybe try with a different device?

**Comment by MaximilianKeppeler** [comment]
I only have one device, a Nexus 6P. With a float value of 10, the onFar Method is not even triggered anymore. (The onNear method is still triggered, but at the same distance, as without a threshold input at all.)

Which device do you have?

**Comment by nisrulz** [comment]
Closing this issue as there isn't any direct possible solution to getting proximity updates from the proximity sensor.i.e it's a hardware limitation on what kind of proximity sensor a device has. 

A possible solution can be using the camera to measure the distance but that's a far-fetched solution taking into account what the goals of the library are now.

If in future it makes sense, will open up a new issue for the same.
