### ISSUE TITLE
Chop Detection

### ISSUE THREAD

**Issue by indianpoptart** [nisrulz/sensey#15]
Is there a way to add a chop detection like the Motorola Flashlight chop detection, or if sensey already does it. Thanks

**Comment by nisrulz** [comment]
@indianpoptart Can you explain what you mean by "Chop" Detection.

**Comment by indianpoptart** [comment]
Here's a short video:
[Chop Detection](https://www.youtube.com/watch?v=edtCMqK8Rn8)

**Comment by nisrulz** [comment]
@indianpoptart  the latest release(1.6.0) has the option to detect chop gesture.

closing as implemented.

**Comment by rameshmkll** [comment]
Chop is not working
  Sensey.getInstance().init(DashBoardActivity.this);
chopListener=new ChopDetector.ChopListener() {
            @Override public void onChop() {
                // Chop gesture detected, do something
                Toast.makeText(mMyApp, "chop", Toast.LENGTH_LONG).show();
                Log.i("chop","started");
            }
        };
        Sensey.getInstance().startChopDetection(chopListener);
