### ISSUE TITLE
What is Wrist Twist Detection？

### ISSUE THREAD

**Issue by maoqis** [nisrulz/sensey#22]
How can i touch off Wrist Twist Detection by moving screen？

**Comment by nisrulz** [comment]
Hi @maoqis, you can checkout this video on yourtube to see how to do a wrist twist gesture

https://www.youtube.com/watch?v=P95eCwkPS4w

**Comment by maoqis** [comment]
thanks!

**Comment by nisrulz** [comment]
Closing as I am assuming this works for you 😄
