### ISSUE TITLE
I'm Using your library now !

### ISSUE THREAD

**Issue by Vel-San** [nisrulz/sensey#35]
I Just added your library to my app ( Shake detection to be exact ) and it's working flawlessly ! already included the library name in my app as well.

[Get Off Your Phone - Play Store](https://play.google.com/store/apps/details?id=com.nephi.getoffyourphone)

Thanks so much for such an excellent library mate ! Keep it up.

If you need more information please tell me :)

**Comment by nisrulz** [comment]
Hi @Alikaraki95, thanks you😺 
I will add your app under my readme too 😄 
If you find any issues, please open up an issue and I would try my best to resolve it asap.

P.S: A brand new version of Sensey should be live in the new year 2018, so keep a look out for it. A lot of things coming to it.
