### ISSUE TITLE
feature Update release version

### ISSUE THREAD

**Issue by Mir1001** [nisrulz/sensey#55]
Thanks for the great work. 

I have noticed that the master branch is quite old compared to the development one. Is it possible to make some release upgrade?

**Comment by nisrulz** [comment]
Hi @Mir1001 there is no big update that is in the `develop` branch, this is why there has been no release. That branch is basically me doing some cleanup and updating project/sample app but not the library. 

However if it helps, I can make a point release with whatever is in the `develop` branch.

One of things I wanted to do is revamp this library to follow patterns that is common nowadays. For the most parts this library is still useable, but maybe the syntax is not "modern".

**Comment by Mir1001** [comment]
Since the last release is 3 years old, I think that the new release will give a signal that this great project is not dead. You can name it minor 1.8.1. For a more "modern" version, you can start with 2.0 ;) Please do it.

**Comment by nisrulz** [comment]
I have made a new release 1.9.0 🙇🏻‍♂️
I haven't been able to do much testing on my own, so if you find any issues please file them in the issue tracker.
