### ISSUE TITLE
Shake detection to sensitive 

### ISSUE THREAD

**Issue by branemk** [nisrulz/sensey#6]
Can you add option for changing sensitivity to shake detection ? Right now is to sensitive it detect when I pick up phone from table.

**Comment by nisrulz** [comment]
@branemk Can you please explain the issue in a more verbose manner.

**Comment by branemk** [comment]
@nisrulz I am talking about being able to set how much motion to detect. 

As you can see here https://github.com/nisrulz/sensey/blob/develop/library/src/main/java/com/github/nisrulz/sensey/ShakeDetector.java 

you have commented the line saying " Make this higher or lower according to how much
      motion you want to detect" , so I am asking for option to change that number.

**Comment by nisrulz** [comment]
@branemk got it. I will provide an option to configure it in the next release.

**Comment by nisrulz** [comment]
Fixed in 7c5e362b92133890e1798ef2beb451d23674a08a
