### ISSUE TITLE
"Swipe left"/"Swipe right" does not work correctly

### ISSUE THREAD

**Issue by programmerr47** [nisrulz/sensey#7]
Tested sample app on Nexus 5, Android 6.0. Try to swipe to right, it shows "Swipe left" label. Moreover when try to swipe to top or bottom, it shows "swipe left".

**Comment by nisrulz** [comment]
The code is in `develop` branch, not fully functional. The final `release` will have it working.

**Comment by programmerr47** [comment]
Hi. Thank you for your reply. I've already have, as I think, fix for that. And also I wrote tests for all classes. If you don't mind, I would like to make pull request.

**Comment by nisrulz** [comment]
All pull request/contribution are welcome. Go ahead and send it.

**Comment by nisrulz** [comment]
Code merged from pull request https://github.com/nisrulz/sensey/pull/8 , some fixes added and code cleanup done and new version is released at commit 32edad619d04ae79153d512a8506f4f58f3940f7

Closing this issue as the latest version `1.3.0` includes all fixes and solves this issue
